---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`soma_longitudes` é uma função"
  checked: true
- value: "`soma_longitudes` tem dois parâmetros"
  checked: true
- value: "`soma_longitudes` pode ser invocada com 2 argumentos"
  checked: true
- value: se escrevemos `soma_longitudes("aprendendo", "programação")`, `"aprendendo"`
    será o primeiro argumento e `"programação"`, o segundo
  checked: true
name: Funções com buraquinhos
