---
locale: pt
tags: []
layout: input_right
editor: code
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
name: Entre os números e a parede
