---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Ambas começam com `def` seguido pelo nome da função
  checked: true
- value: Ambas começam com `def` seguido pelos dois pontos
  checked: false
- value: Ambas têm um `return` na primeira linha
  checked: false
- value: Ambas têm um `return` na última linha
  checked: true
- value: Ambas terminam a primeira linha com dois pontos
  checked: true
- value: Ambas iniciam a segunda linha alinhada à margem
  checked: false
name: O jogo das semelhanças
